-- Generated by nwg-displays on 2026-09-15 at 21:34:06. Do not edit manually.

hl.monitor({
    output = "desc:Iiyama North America PL2741QS 12745613A1329",
    mode = "2560x1440@144.0",
    position = "1920x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "desc:LG Electronics LG FULL HD 0x0027CA47",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
    vrr = 0
})
